name: Publish demo to vercel
# Based on TIL file: https://github.com/simonw/til/blob/main/.github/workflows/build.yml

# Running this from here because Vercel build system seems tailored to publishing static sites, and wasn't handling a custom build function well.
# in future, re-investigate using vercel to handle deployment previews.
on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        path: main
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install pip version
      run: |
        python -m pip install --upgrade pip
    - name: Install npm dependencies
      run: yarn
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build plugin static files
      run: yarn run build

    # note this step manages its own dependencies
    - name: Deploy Datasette using Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        cd main
        make publish-vercel
